### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by ghost** [CodeXTF2/Burp2Malleable#4]
from malleablec2 import Profile
ModuleNotFoundError: No module named 'malleablec2'

when I try to install it via pip3 , the module is not available.

**Comment by CodeXTF2** [comment]
oh its pymalleablec2. il add it to reqs tmw

**Comment by CodeXTF2** [comment]
https://github.com/Porchetta-Industries/pyMalleableC2

**Comment by CodeXTF2** [comment]
fixed with 976db7ba93127a5bb9eda1876588f93586a5b87c
